@startuml
left to right direction

' --- ACTORES ---
actor "Socio" as Socio
actor "Entrenador" as Entrenador

' --- SISTEMA (Frontera) ---
rectangle "App Gimnasio" {
  
  ' Funciones Comunes (Heredadas de Usuario)
  usecase "Iniciar Sesión (Login)" as Login

  ' Funciones del Socio
  usecase "Consultar su Suscripción" as VerSuscripcion
  usecase "Ver Horario de Sesiones" as VerHorario
  usecase "Realizar Reserva" as Reservar
  usecase "Cancelar Reserva" as Cancelar

  ' Funciones del Entrenador (Modo Gestión)
  usecase "Gestionar Clases (Catálogo)" as GestClases
  usecase "Programar Sesiones" as ProgSesiones
  usecase "Consultar Asistencia de Reservas" as VerAsistencia
}

' --- CONEXIONES ---
' Ambos actores necesitan hacer login
Socio --> Login
Entrenador --> Login

' Acciones específicas del Socio
Socio --> VerSuscripcion
Socio --> VerHorario
Socio --> Reservar
Socio --> Cancelar

' Acciones específicas del Entrenador
Entrenador --> GestClases
Entrenador --> ProgSesiones
Entrenador --> VerAsistencia

@enduml