@startuml
title Diagrama de Clases (Modelos) - Gym APP

skinparam classAttributeIconSize 0

package "model.enums" {
    enum EstadoUsuario {
        ACTIVO
        INACTIVO
    }
    enum EstadoSuscripcion {
        ACTIVA
        VENCIDA
        CANCELADA
        ARCHIVADA
    }
    enum EstadoSesion {
        PROGRAMADA
        EN_CURSO
        FINALIZADA
        CANCELADA
    }
    enum EstadoReserva {
        PENDIENTE
        CONFIRMADA
        REALIZADA
        CANCELADA
        AUSENTE
    }
    enum RolUsuario {
        SOCIO
        ENTRENADOR
        SECRETARIO
    }
    enum TurnoTrabajo {
        MAÑANA
        TARDE
        NOCHE
    }
}

package "model" {
    
    abstract class Usuario {
        - idUsuario : int
        - nombre : String
        - apellido : String
        - email : String
        - password : String
        - rol : RolUsuario
        - estado : EstadoUsuario
    }

    class Socio extends Usuario {
        - telefono : String
        - fechaAlta : LocalDate
    }

    class Entrenador extends Usuario {
        - especialidad : String
    }

    class Secretario extends Usuario {
        - turno : TurnoTrabajo
    }

    class Clase {
        - idClase : int
        - nombre : String
        - aforoMax : int
    }

    class Sesion {
        - idSesion : int
        - idClase : int
        - idEntrenador : int
        - inicio : LocalDateTime
        - fin : LocalDateTime
        - sala : String
        - estado : EstadoSesion
    }

    class Reserva {
        - idReserva : int
        - idSocio : int
        - idSesion : int
        - fechaReserva : LocalDateTime
        - estado : EstadoReserva
    }

    class Plan {
        - idPlan : int
        - nombre : String
        - precio : double
        - activo : boolean
    }

    class Suscripcion {
        - idSuscripcion : int
        - idSocio : int
        - idPlan : int
        - fechaInicio : LocalDate
        - fechaFin : LocalDate
        - estado : EstadoSuscripcion
    }
}



@enduml