@startuml
title Diagrama de Clases (Modelos) - Gym APP

skinparam classAttributeIconSize 0

package "model.enums" {
    enum EstadoUsuario {
        ACTIVO
        INACTIVO
    }
    enum EstadoPlan {
        ACTIVO
        INACTIVO
    }
    enum EstadoSuscripcion {
        ACTIVA
        VENCIDA
        CANCELADA
    }
    enum EstadoReserva {
        RESERVADA
        ASISTIDA
        AUSENTE
        CANCELADA
    }
    enum SalaGimnasio {
        SALA_PRINCIPAL
        SALA_MULTIUSOS
        SALA_ZEN
        SALA_SPINNING
    }
}

package "model" {
    
    abstract class Usuario {
        - idUsuario : int
        - nombre : String
        - apellido : String
        - email : String
        - password : String
        - telefono : String
        - estado : EstadoUsuario
    }

    class Admin extends Usuario {
    }

    class Socio extends Usuario {
        - fechaAlta : LocalDate
    }

    class Entrenador extends Usuario {
        - especialidad : String
    }

    class Secretario extends Usuario {
        - turno : String
    }

    class Clase {
        - idClase : int
        - nombre : String
        - aforoMax : int
    }

    class Sesion {
        - idSesion : int
        - idClase : int
        - idEntrenador : int
        - inicio : LocalDateTime
        - fin : LocalDateTime
        - sala : String
        - estado : String
    }

    class Reserva {
        - idSocio : int
        - idSesion : int
        - fechaReserva : LocalDateTime
        - estado : EstadoReserva
    }

    class Plan {
        - idPlan : int
        - nombre : String
        - precioMensual : double
        - estado : EstadoPlan
    }

    class Suscripcion {
        - idSuscripcion : int
        - idSocio : int
        - idPlan : int
        - fechaInicio : LocalDate
        - fechaFin : LocalDate
        - estado : EstadoSuscripcion
    }
}
@enduml