@startuml
title Proceso de Alta de Usuario (Secretario / Admin)

start

:Acceder a Gestión de Socios / Entrenadores;
:Seleccionar "Alta de nuevo...";
:Introducir Datos Personales y Rol;

:Insertar Registro en Base de Datos;

if (¿El correo electrónico ya existe en BD?) then (Sí)
  :La BD rechaza el registro;
  :Mostrar aviso "Hubo un problema al registrar"; <<#red>>
else (No)
  :El sistema asigna estado ACTIVO por defecto;
  :Mostrar mensaje "Alta completada con éxito"; <<#green>>
endif

stop
@enduml