@startuml


title Proceso de Inicio de Sesión (Login)

start

:Ejecutar Sistema (Main);
:Solicitar Email y Contraseña (LoginController);

:Consultar Base de Datos;

if (¿Email "admin" y Password "admin"?) then (Sí)
  :Generar SuperUsuario en Memoria;
  :Mostrar Panel de Control ADMIN; <<#green>>
else (No)
  if (¿Credenciales correctas?) then (Sí)
    if (¿El estado es ACTIVO?) then (Sí)
      :Redirigir al Panel según Rol (Socio, Entrenador...); <<#green>>
    else (No)
      :Mostrar "Acceso Denegado: Cuenta inactiva"; <<#red>>
    endif
  else (No)
    :Mostrar "Credenciales incorrectas"; <<#red>>
  endif
endif

stop
@enduml  