@startuml
title Proceso de Gestion de Suscripción a un Socio

start

:Acceder a "Gestión de Suscripciones";
:Seleccionar "Vender nueva suscripción";

:Solicitar ID de Socio;
if (¿El Socio existe en la BD?) then (No)
  :Mostrar error "No existe el socio"; <<#red>>
  stop
else (Sí)
endif

:Solicitar ID del Plan;
if (¿El Plan existe en la BD?) then (No)
  :Mostrar error "No existe el plan"; <<#red>>
  stop
else (Sí)
endif

:Generar Fecha de Inicio (Hoy) y Fin (+1 Mes);
:Insertar registro en la BD (Estado: ACTIVA);
:Mostrar "Venta completada"; <<#green>>

stop
@enduml