@startuml
title Proceso de Cancelar Reserva (Socio / Secretario / Admin)

start

if (¿Rol del Usuario actual?) then (Socio)
  :Acceder a "Mis Reservas";
  :Seleccionar la reserva a cancelar;
else (Secretario / Admin)
  :Acceder a "Gestión de Reservas";
  :Introducir ID del Socio e ID de la Sesión;
endif

:Buscar Reserva en la Base de Datos;

if (¿La reserva existe?) then (No)
  :Mostrar "No se ha encontrado ninguna reserva"; <<#red>>
else (Sí)
  :Modificar el estado de la reserva a CANCELADA;
  :Actualizar el registro en la Base de Datos (UPDATE);
  :Mostrar "El estado se ha actualizado a: CANCELADA"; <<#green>>
endif

stop
@enduml