title Proceso de Añadir Nueva Clase al Catálogo (Secretario)

start

:Acceder a "Gestión del Catálogo";
:Seleccionar "Añadir Nueva Actividad";
note right: Ejemplo: "Zumba", "Spinning"
:Introducir Nombre y Aforo Base;

if (¿El nombre ya existe en el catálogo?) then (Sí)
  :Mostrar error "Actividad ya registrada"; <<#red>>
  
else (No)
  :Generar nuevo id_clase;
  :INSERT en tabla 'clase';
  :Confirmar "Actividad añadida con éxito"; <<#green>>
endif

stop
@enduml