@startuml
title Proceso de Administración de Planes

start

:Acceder a "Gestión de Planes y Tarifas";
:Seleccionar "Crear un nuevo plan";
:Introducir Nombre del Plan;

:Solicitar Precio Mensual;
if (¿Formato de precio correcto?) then (No)
  :Mostrar "Error: Usa un punto para decimales"; <<#red>>
else (Sí)
  :Establecer estado inicial como ACTIVO;
  :Guardar en Base de Datos;
  :Mostrar "Plan registrado y listo para venderse"; <<#green>>
endif

stop
@enduml