@startuml
title Diagrama de Secuencia: Proceso de Login - Gym APP

autonumber
actor "Usuario\n(Socio/Staff)" as User
boundary "PantallaLogin\n(Vista)" as Vista
control "LoginController\n(Controlador)" as Controller
participant "UsuarioDAO\n(Capa DAO)" as DAO
database "Supabase\n(PostgreSQL)" as DB

User -> Vista : Introduce email y contraseña
activate Vista

Vista -> Controller : btnLoginClick(email, pass)
activate Controller

' --- VALIDACIÓN LOCAL (Antes de ir a DB) ---
Controller -> Controller : Validar formato (vacíos)
alt Formato Incorrecto
    Controller -[#orange]-> Vista : <color:orange>Mostrar "Rellena todos los campos"</color>
else Formato Correcto
    
    Controller -> DAO : login(email, pass)
    activate DAO
    DAO -> DB : SELECT * FROM usuario WHERE email=? AND password=?
    activate DB
    DB --> DAO : Retorna datos (o vacío)
    deactivate DB

    alt Credenciales Correctas
        DAO --> Controller : Retorna Objeto Usuario
        Controller -[#green]-> Vista : <color:green>Redirigir al Menú</color>
    else Credenciales Incorrectas
        DAO --> Controller : Retorna null
        Controller -[#red]-> Vista : <color:red>Mostrar "Datos inválidos"</color>
    end
    deactivate DAO
end
deactivate Controller
deactivate Vista
@enduml