@startuml
title Diagrama de Secuencia: Hacer una Reserva - Gym APP

autonumber
actor "Socio" as User
boundary "PantallaReserva\n(Vista)" as Vista
control "ReservaController\n(Controlador)" as Controller
participant "SuscripcionDAO\n(Capa DAO)" as SuscDAO
participant "ReservaDAO\n(Capa DAO)" as ResDAO
database "Supabase\n(PostgreSQL)" as DB

User -> Vista : Clic en "Reservar" (idSesion)
activate Vista

Vista -> Controller : procesarReserva(idSocio, idSesion)
activate Controller

' --- 1. FILTRO DE PREVENCIÓN: ¿Ha pagado el socio? ---
Controller -> SuscDAO : consultarActiva(idSocio)
activate SuscDAO
SuscDAO -> DB : SELECT * FROM suscripcion WHERE id_socio=? AND fecha_fin >= HOY
activate DB
DB --> SuscDAO : Retorna Suscripcion (o vacío)
deactivate DB
SuscDAO --> Controller : Objeto Suscripcion (o null)
deactivate SuscDAO

alt Sin suscripción activa
    Controller -[#red]-> Vista : <color:red>Mostrar error "Debes contratar un plan activo"</color>
else Suscripción válida

    ' --- 2. FILTRO DE AFORO: ¿Hay hueco en la clase? ---
    Controller -> ResDAO : listarPorSesion(idSesion)
    activate ResDAO
    ResDAO -> DB : SELECT * FROM reserva WHERE id_sesion=?
    activate DB
    DB --> ResDAO : Lista de registros
    deactivate DB
    ResDAO --> Controller : List<Reserva> (Ej: lista de 15 personas)
    deactivate ResDAO

    Controller -> Controller : Comprobar: (tamaño de la lista < aforoMax)

    alt Aforo Lleno
        Controller -[#orange]-> Vista : <color:orange>Mostrar error "La clase está completa"</color>
    else Hay Plazas Disponibles

        ' --- 3. INSERCIÓN: Todo correcto, guardamos la reserva ---
        Controller -[#green]-> Vista : <color:green>Mostrar mensaje "Reserva confirmada con éxito"</color>


    end
end

deactivate Controller
deactivate Vista

@enduml