@startuml
title Secuencia: Reservar_Sesion

' --- PARTICIPANTES ---
actor Socio
boundary "MenuReserva" as Vista
control "ReservaController" as Controlador
entity "SuscripcionDAO" as SuscDAO
entity "SesionDAO" as SesionDAO
entity "ReservaDAO" as ResDAO
database "PostgreSQL" as BD

' --- FLUJO 1: Mostrar Catálogo ---
Socio -> Vista: Selecciona "Reservar Sesión"
activate Vista

Vista -> Controlador: obtenerSesionesDisponibles()
activate Controlador

Controlador -> SesionDAO: consultarSesionesActivas()
activate SesionDAO
SesionDAO -> BD: SELECT * FROM sesion
activate BD
BD --> SesionDAO: Devuelve horarios
deactivate BD
SesionDAO --> Controlador: retorna Lista<Sesion>
deactivate SesionDAO

Controlador --> Vista: retorna Lista<Sesion>
deactivate Controlador

Vista --> Socio: Muestra calendario de clases

' --- FLUJO 2: Proceso de Reserva ---
Socio -> Vista: Elige una sesión concreta
Vista -> Controlador: procesarReserva(idSocio, idSesion)
activate Controlador

' Validación 1: Suscripción
Controlador -> SuscDAO: verificarSuscripcionActiva(idSocio)
activate SuscDAO
SuscDAO -> BD: SELECT estado FROM suscripcion WHERE id_socio = ?
activate BD
BD --> SuscDAO: Devuelve estado
deactivate BD
SuscDAO --> Controlador: retorna boolean
deactivate SuscDAO

alt No tiene suscripción activa
    Controlador --> Vista: retorna error_suscripcion
    Vista --> Socio: Muestra "Error: Necesita contratar un Plan"

else Sí tiene suscripción activa
    ' Validación 2: Aforo
    Controlador -> SesionDAO: comprobarAforoLibre(idSesion)
    activate SesionDAO
    SesionDAO -> BD: SELECT aforo_max - ocupados FROM sesion...
    activate BD
    BD --> SesionDAO: Devuelve plazas libres
    deactivate BD
    SesionDAO --> Controlador: retorna boolean
    deactivate SesionDAO

    alt Sin plazas libres
        Controlador --> Vista: retorna error_aforo
        Vista --> Socio: Muestra "Error: La sesión está completa"
        
    else Hay plazas libres
        ' Inserción final
        Controlador -> ResDAO: registrarReserva(idSocio, idSesion)
        activate ResDAO
        ResDAO -> BD: INSERT INTO reserva (...)
        activate BD
        BD --> ResDAO: Confirmación (1 fila afectada)
        deactivate BD
        ResDAO --> Controlador: retorna true
        deactivate ResDAO
        
        Controlador --> Vista: retorna confirmacion_OK
        Vista --> Socio: Muestra "Reserva Confirmada con éxito"
    end
end

deactivate Controlador
deactivate Vista

@enduml