@startuml
title Secuencia: Programar_Sesion

' --- PARTICIPANTES ---
actor Entrenador
boundary "MenuProgramacion" as Vista
control "ProgramacionController" as Controlador
entity "ClaseDAO" as ClaseDAO
entity "SesionDAO" as SesionDAO
database "PostgreSQL" as BD

' --- FLUJO 1: Mostrar catálogo de clases ---
Entrenador -> Vista: Selecciona "Programar Nueva Sesión"
activate Vista

Vista -> Controlador: obtenerClasesDisponibles()
activate Controlador

Controlador -> ClaseDAO: obtenerCatalogoClases()
activate ClaseDAO
ClaseDAO -> BD: SELECT * FROM clase
activate BD
BD --> ClaseDAO: Devuelve catálogo de disciplinas
deactivate BD
ClaseDAO --> Controlador: retorna Lista<Clase>
deactivate ClaseDAO

Controlador --> Vista: retorna Lista<Clase>
deactivate Controlador

Vista --> Entrenador: Muestra opciones (Yoga, CrossFit, etc.)

' --- FLUJO 2: Proceso de creación ---
Entrenador -> Vista: Introduce datos (idClase, inicio, fin, sala)
Vista -> Controlador: programarSesion(idEntrenador, idClase, inicio, fin, sala)
activate Controlador

' Validación de conflictos
Controlador -> SesionDAO: verificarConflictos(idEntrenador, inicio, sala)
activate SesionDAO
SesionDAO -> BD: SELECT count(*) FROM sesion WHERE sala = ? AND inicio = ?...
activate BD
BD --> SesionDAO: Devuelve número de conflictos
deactivate BD
SesionDAO --> Controlador: retorna hay_conflicto (boolean)
deactivate SesionDAO

alt Conflicto de horario o sala
    Controlador --> Vista: retorna error_conflicto
    Vista --> Entrenador: Muestra "Error: El horario o la sala ya están ocupados"
    
else Todo libre (Sin conflictos)
    ' Inserción final de la sesión
    Controlador -> SesionDAO: registrarSesion(idEntrenador, idClase, inicio, fin, sala)
    activate SesionDAO
    SesionDAO -> BD: INSERT INTO sesion (...)
    activate BD
    BD --> SesionDAO: Confirmación (1 fila afectada)
    deactivate BD
    SesionDAO --> Controlador: retorna true
    deactivate SesionDAO
    
    Controlador --> Vista: retorna confirmacion_OK
    Vista --> Entrenador: Muestra "Sesión programada con éxito"
end

deactivate Controlador
deactivate Vista

@enduml